group=com.velocitypowered
version=4.1.2-SNAPSHOT

org.gradle.cache=true
org.gradle.caching=true
org.gradle.tooling.parallel=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache-problems=warn
org.gradle.configuration-cache.problems=warn
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4048m -Dfile.encoding=UTF-8
org.gradle.vfs.watch=false
